services:
  gf_rang_bot:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - gf_rang_db
    restart: always

  gf_rang_db:
    image: postgres:17
    env_file:
      - .env 
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
