"""empty message

Revision ID: 4c35e875738f
Revises: 2b881e2b1233
Create Date: 2025-08-04 15:52:07.260090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c35e875738f'
down_revision: Union[str, Sequence[str], None] = '2b881e2b1233'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('visibility', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'visibility')
    # ### end Alembic commands ###
