"""empty message

Revision ID: efc82bc9463f
Revises: db724ff49597
Create Date: 2025-08-05 17:19:40.062147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efc82bc9463f'
down_revision: Union[str, Sequence[str], None] = 'db724ff49597'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_approved', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('attempt_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_attempt_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_attempt_date')
    op.drop_column('users', 'attempt_count')
    op.drop_column('users', 'is_approved')
    # ### end Alembic commands ###
